name: Synchronous # 部署

'on':
  - workflow_dispatch
  - push

jobs:
  workers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout # Checkout 仓库
      uses: actions/checkout@v3
      with:
        ref: main
        
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        repository: qystudio0/qystudio0.github.io
        path: public

    - name: Deploy to Cloudflare Workers
      uses: cloudflare/wrangler-action@1.3.0
      with:
        apiToken: ${{ secrets.CF_WORKERS_TOKEN }}

  ftp1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        repository: qystudio0/qystudio0.github.io

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
